# pages:
#   stage: deploy
#   script:
#     - mkdir .public
#     - cp -r * .public
#     - mv .public public
#   artifacts:
#     paths:
#       - public
#   only:
#     - main

    pages:
  stage: deploy
  script:
    - mkdir public
    - cp -r index.html css js images fonts public
  artifacts:
    paths:
      - public
  only:
    - main